
boolean[][] categories = {  {true,false,false,false,false,false,false,false},
                            {true,false,false,false,false,false,false,false},
                            {true,false,false,false,false,false,false,false},
                            {true,false,false,false,false,false,false,false},
                            {true,false,false,false,false,false,false,false},
//                            {true,false,false,false,false,false,false,false},
                            
                            {false,true,false,false,false,false,false,false},
                            {false,true,false,false,false,false,false,false},
                            {false,true,false,false,false,false,false,false},
                            {false,true,false,false,false,false,false,false},
                            {false,true,false,false,false,false,false,false},
//                            {false,true,false,false,false,false,false,false},
                            
                            {false,false,true,false,false,false,false,false},
                            {false,false,true,false,false,false,false,false},
                            {false,false,true,false,false,false,false,false},
                            {false,false,true,false,false,false,false,false},
                            {false,false,true,false,false,false,false,false},
//                            {false,false,true,false,false,false,false,false},
                            
                            {false,false,false,true,false,false,false,false},
                            {false,false,false,true,false,false,false,false},
                            {false,false,false,true,false,false,false,false},
                            {false,false,false,true,false,false,false,false},
                            {false,false,false,true,false,false,false,false},
//                            {false,false,false,true,false,false,false,false},
                            
                            {false,false,false,false,true,false,false,false},
                            {false,false,false,false,true,false,false,false},
                            {false,false,false,false,true,false,false,false},
                            {false,false,false,false,true,false,false,false},
                            {false,false,false,false,true,false,false,false},
//                            {false,false,false,false,true,false,false,false},
                            
                            {false,false,false,false,false,true,false,false},
                            {false,false,false,false,false,true,false,false},
                            {false,false,false,false,false,true,false,false},
                            {false,false,false,false,false,true,false,false},
                            {false,false,false,false,false,true,false,false},
//                            {false,false,false,false,false,true,false,false},
                            
                            {false,false,false,false,false,false,true,false},
                            {false,false,false,false,false,false,true,false},
                            {false,false,false,false,false,false,true,false},
                            {false,false,false,false,false,false,true,false},
                            {false,false,false,false,false,false,true,false},
//                            {false,false,false,false,false,false,true,false},
                            
                            {false,false,false,false,false,false,false,true},
                            {false,false,false,false,false,false,false,true},
                            {false,false,false,false,false,false,false,true},
                            {false,false,false,false,false,false,false,true},
                            {false,false,false,false,false,false,false,true},
//                            {false,false,false,false,false,false,false,true},
                            
                            };
